"""campos adicionales de asignatura

Revision ID: 252d9a1be8ec
Revises: 66dceb0143da
Create Date: 2026-08-12 15:40:43.684528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252d9a1be8ec'
down_revision: Union[str, None] = '66dceb0143da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignatura', sa.Column('horas_texto', sa.String(length=200), nullable=True))
    op.add_column('asignatura', sa.Column('horas_total', sa.Integer(), nullable=True))
    op.add_column('asignatura', sa.Column('horas_acd', sa.Integer(), nullable=True))
    op.add_column('asignatura', sa.Column('horas_ape', sa.Integer(), nullable=True))
    op.add_column('asignatura', sa.Column('horas_aa', sa.Integer(), nullable=True))
    op.add_column('asignatura', sa.Column('tipo_plantilla', sa.String(length=60), nullable=True))
    op.add_column('asignatura', sa.Column('propia_de_carrera', sa.String(length=20), nullable=True))
    op.add_column('asignatura', sa.Column('carreras_oferta', sa.Integer(), nullable=True))
    op.add_column('asignatura', sa.Column('carrera_origen', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignatura', 'carrera_origen')
    op.drop_column('asignatura', 'carreras_oferta')
    op.drop_column('asignatura', 'propia_de_carrera')
    op.drop_column('asignatura', 'tipo_plantilla')
    op.drop_column('asignatura', 'horas_aa')
    op.drop_column('asignatura', 'horas_ape')
    op.drop_column('asignatura', 'horas_acd')
    op.drop_column('asignatura', 'horas_total')
    op.drop_column('asignatura', 'horas_texto')
    # ### end Alembic commands ###
