"""token de recuperacion

Revision ID: 33dc328e7bb3
Revises: bd19d4158c6e
Create Date: 2026-08-11 23:21:29.992088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dc328e7bb3'
down_revision: Union[str, None] = 'bd19d4158c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_recuperacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_token', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_solicitud', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_recuperacion_hash_token'), 'token_recuperacion', ['hash_token'], unique=True)
    op.create_index(op.f('ix_token_recuperacion_usuario_id'), 'token_recuperacion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_recuperacion_usuario_id'), table_name='token_recuperacion')
    op.drop_index(op.f('ix_token_recuperacion_hash_token'), table_name='token_recuperacion')
    op.drop_table('token_recuperacion')
    # ### end Alembic commands ###
