"""guia matriz y semanas

Revision ID: 66dceb0143da
Revises: a49f12a28036
Create Date: 2026-08-12 10:55:44.836645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66dceb0143da'
down_revision: Union[str, None] = 'a49f12a28036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriz_planificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asignatura_id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('semanas_totales', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('subida_por_id', sa.UUID(), nullable=False),
    sa.Column('subida_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_academico.id'], ),
    sa.ForeignKeyConstraint(['subida_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignatura_id', 'periodo_id')
    )
    op.create_index(op.f('ix_matriz_planificacion_asignatura_id'), 'matriz_planificacion', ['asignatura_id'], unique=False)
    op.create_index(op.f('ix_matriz_planificacion_periodo_id'), 'matriz_planificacion', ['periodo_id'], unique=False)
    op.create_table('fila_matriz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matriz_id', sa.UUID(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('resultado_aprendizaje', sa.Text(), nullable=True),
    sa.Column('unidad_contenido', sa.Text(), nullable=False),
    sa.Column('metodologia', sa.Text(), nullable=True),
    sa.Column('actividades', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz_planificacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriz_id', 'semana')
    )
    op.create_index(op.f('ix_fila_matriz_matriz_id'), 'fila_matriz', ['matriz_id'], unique=False)
    op.create_table('guia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asignatura_id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('matriz_id', sa.UUID(), nullable=True),
    sa.Column('semanas_totales', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('creada_por_id', sa.UUID(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz_planificacion.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_academico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignatura_id', 'periodo_id')
    )
    op.create_index(op.f('ix_guia_asignatura_id'), 'guia', ['asignatura_id'], unique=False)
    op.create_index(op.f('ix_guia_estado'), 'guia', ['estado'], unique=False)
    op.create_index(op.f('ix_guia_periodo_id'), 'guia', ['periodo_id'], unique=False)
    op.create_table('semana_guia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guia_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('bloques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intentos_usados', sa.Integer(), nullable=False),
    sa.Column('intentos_concedidos', sa.Integer(), nullable=False),
    sa.Column('aprobada_por_id', sa.UUID(), nullable=True),
    sa.Column('aprobada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobada_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['guia_id'], ['guia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guia_id', 'numero')
    )
    op.create_index(op.f('ix_semana_guia_guia_id'), 'semana_guia', ['guia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semana_guia_guia_id'), table_name='semana_guia')
    op.drop_table('semana_guia')
    op.drop_index(op.f('ix_guia_periodo_id'), table_name='guia')
    op.drop_index(op.f('ix_guia_estado'), table_name='guia')
    op.drop_index(op.f('ix_guia_asignatura_id'), table_name='guia')
    op.drop_table('guia')
    op.drop_index(op.f('ix_fila_matriz_matriz_id'), table_name='fila_matriz')
    op.drop_table('fila_matriz')
    op.drop_index(op.f('ix_matriz_planificacion_periodo_id'), table_name='matriz_planificacion')
    op.drop_index(op.f('ix_matriz_planificacion_asignatura_id'), table_name='matriz_planificacion')
    op.drop_table('matriz_planificacion')
    # ### end Alembic commands ###
