"""reglas documentos e indicadores

Revision ID: 68728b0d342b
Revises: 252d9a1be8ec
Create Date: 2026-08-13 00:24:26.159445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68728b0d342b'
down_revision: Union[str, None] = '252d9a1be8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_conocimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('aplica_a_todo', sa.Boolean(), nullable=False),
    sa.Column('niveles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('modalidades', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('duraciones', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('tipos_asignatura', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('creado_por_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave', 'version')
    )
    op.create_index(op.f('ix_documento_conocimiento_clave'), 'documento_conocimiento', ['clave'], unique=False)
    op.create_index(op.f('ix_documento_conocimiento_estado'), 'documento_conocimiento', ['estado'], unique=False)
    op.create_table('especificacion_generacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('niveles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('modalidades', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('duraciones', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('tipos_asignatura', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('creada_por_id', sa.UUID(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave', 'version')
    )
    op.create_index(op.f('ix_especificacion_generacion_clave'), 'especificacion_generacion', ['clave'], unique=False)
    op.create_index(op.f('ix_especificacion_generacion_estado'), 'especificacion_generacion', ['estado'], unique=False)
    op.create_table('version_indicadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creada_por_id', sa.UUID(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_version_indicadores_estado'), 'version_indicadores', ['estado'], unique=False)
    op.create_table('indicador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['version_indicadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'codigo')
    )
    op.create_index(op.f('ix_indicador_version_id'), 'indicador', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicador_version_id'), table_name='indicador')
    op.drop_table('indicador')
    op.drop_index(op.f('ix_version_indicadores_estado'), table_name='version_indicadores')
    op.drop_table('version_indicadores')
    op.drop_index(op.f('ix_especificacion_generacion_estado'), table_name='especificacion_generacion')
    op.drop_index(op.f('ix_especificacion_generacion_clave'), table_name='especificacion_generacion')
    op.drop_table('especificacion_generacion')
    op.drop_index(op.f('ix_documento_conocimiento_estado'), table_name='documento_conocimiento')
    op.drop_index(op.f('ix_documento_conocimiento_clave'), table_name='documento_conocimiento')
    op.drop_table('documento_conocimiento')
    # ### end Alembic commands ###
