"""catalogo academico y asignaciones

Revision ID: a49f12a28036
Revises: 33dc328e7bb3
Create Date: 2026-08-12 08:31:57.620064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49f12a28036'
down_revision: Union[str, None] = '33dc328e7bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facultad_nombre'), 'facultad', ['nombre'], unique=True)
    op.create_table('periodo_academico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodo_academico_activo'), 'periodo_academico', ['activo'], unique=False)
    op.create_index(op.f('ix_periodo_academico_nombre'), 'periodo_academico', ['nombre'], unique=True)
    op.create_table('carrera',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facultad_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('departamento', sa.String(length=200), nullable=True),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.Column('modalidad', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facultad_id', 'nombre')
    )
    op.create_index(op.f('ix_carrera_nombre'), 'carrera', ['nombre'], unique=False)
    op.create_table('asignatura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('carrera_id', sa.UUID(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('ciclo', sa.String(length=20), nullable=True),
    sa.Column('campo_formacion', sa.String(length=120), nullable=True),
    sa.Column('url_canvas', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignatura_codigo'), 'asignatura', ['codigo'], unique=True)
    op.create_table('asignacion_docente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('asignatura_id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('rol_en_asignatura', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_academico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docente_id', 'asignatura_id', 'periodo_id')
    )
    op.create_index(op.f('ix_asignacion_docente_asignatura_id'), 'asignacion_docente', ['asignatura_id'], unique=False)
    op.create_index(op.f('ix_asignacion_docente_docente_id'), 'asignacion_docente', ['docente_id'], unique=False)
    op.create_index(op.f('ix_asignacion_docente_periodo_id'), 'asignacion_docente', ['periodo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asignacion_docente_periodo_id'), table_name='asignacion_docente')
    op.drop_index(op.f('ix_asignacion_docente_docente_id'), table_name='asignacion_docente')
    op.drop_index(op.f('ix_asignacion_docente_asignatura_id'), table_name='asignacion_docente')
    op.drop_table('asignacion_docente')
    op.drop_index(op.f('ix_asignatura_codigo'), table_name='asignatura')
    op.drop_table('asignatura')
    op.drop_index(op.f('ix_carrera_nombre'), table_name='carrera')
    op.drop_table('carrera')
    op.drop_index(op.f('ix_periodo_academico_nombre'), table_name='periodo_academico')
    op.drop_index(op.f('ix_periodo_academico_activo'), table_name='periodo_academico')
    op.drop_table('periodo_academico')
    op.drop_index(op.f('ix_facultad_nombre'), table_name='facultad')
    op.drop_table('facultad')
    # ### end Alembic commands ###
