"""registro de auditoria

Revision ID: bd19d4158c6e
Revises: c7f209fe1101
Create Date: 2026-08-11 22:56:56.508247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd19d4158c6e'
down_revision: Union[str, None] = 'c7f209fe1101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=40), nullable=True),
    sa.Column('id_entidad', sa.String(length=60), nullable=True),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('agente_usuario', sa.String(length=255), nullable=True),
    sa.Column('ocurrido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_auditoria_accion'), 'registro_auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_actor_id'), 'registro_auditoria', ['actor_id'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_ocurrido_en'), 'registro_auditoria', ['ocurrido_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_auditoria_ocurrido_en'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_actor_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_accion'), table_name='registro_auditoria')
    op.drop_table('registro_auditoria')
    # ### end Alembic commands ###
