"""tabla de sesiones

Revision ID: c7f209fe1101
Revises: 9b5f034fe2b0
Create Date: 2026-08-11 19:13:37.641803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f209fe1101'
down_revision: Union[str, None] = '9b5f034fe2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_token', sa.String(length=64), nullable=False),
    sa.Column('emitida_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('agente_usuario', sa.String(length=255), nullable=True),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_hash_token'), 'sesion', ['hash_token'], unique=True)
    op.create_index(op.f('ix_sesion_usuario_id'), 'sesion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_usuario_id'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_hash_token'), table_name='sesion')
    op.drop_table('sesion')
    # ### end Alembic commands ###
